version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - tomcat
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  tomcat:
    build: ./tomcat
    environment:
      - JAVA_OPTS=-Djava.util.logging.config.file=/usr/local/tomcat/logging.properties
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps

  redis:
    image: redis:6
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampledb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml

  agent:
    build: ./agent
    depends_on:
      - loki
      - promtail
    ports:
      - "5050:5000"
    volumes:
      - ./agent:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/summary"]
      interval: 10s
      timeout: 5s
      retries: 5

  loadgen:
    build: ./load-generator
    depends_on:
      - nginx
