apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: observability-demo
data:
  nginx.conf: |
    events {}

    http {
        upstream observability_apps {
            server app1:8000;
            server app2:8000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://observability_apps;
            }

            location /grafana/ {
                proxy_pass http://grafana:3000/;
                rewrite ^/grafana/(.*)$ /$1 break;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Scheme $scheme;
            }

            location /prometheus/ {
                proxy_pass http://prometheus:9090/;
            }

            location /loki/ {
                proxy_pass http://loki:3100/;
            }
        }
    }