apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: observability-demo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31099