version: '3.9'

x-common-labels: &common_labels
  logging: "promtail"
  env: "dev"           # change to prod/stage as needed
  stack: "demo"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - tomcat
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx         # <-- write logs to host
    labels:
      <<: *common_labels
      app: "nginx"

  tomcat:
    build: ./tomcat
    environment:
      - JAVA_OPTS=-Djava.util.logging.config.file=/usr/local/tomcat/logging.properties
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./logs/tomcat:/usr/local/tomcat/logs   # <-- catalina/out etc.
    labels:
      <<: *common_labels
      app: "tomcat"

  redis:
    image: redis:6
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    labels:
      <<: *common_labels
      app: "redis"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampledb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    labels:
      <<: *common_labels
      app: "mysql"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - ./loki/data:/loki                      # <-- data dir
    labels:
      <<: *common_labels
      app: "loki"

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # docker json logs
      - /var/run/docker.sock:/var/run/docker.sock:ro              # docker SD
      - ./logs:/var/log/app:ro                                    # file logs from services
    labels:
      <<: *common_labels
      app: "promtail"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    labels:
      <<: *common_labels
      app: "grafana"

  agent:
    build: ./agent
    depends_on:
      - loki
      - promtail
    ports:
      - "5050:5000"
    volumes:
      - ./agent:/app
      - ./logs/agent:/app/logs                  # <-- agent file logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      <<: *common_labels
      app: "agent"

  loadgen:
    build: ./load-generator
    depends_on:
      - nginx
    labels:
      <<: *common_labels
      app: "loadgen"