apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: observability-demo
data:
  grafana-datasource-loki.yaml: |
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        isDefault: false
        version: 1
        editable: true
