apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability-demo
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.4.1
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
            - "-config.expand-env=true"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: loki-config