apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability-demo
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info

    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /loki/chunks

    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      chunk_idle_period: 5m
      max_chunk_age: 1h
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    distributor:
      ring:
        kvstore:
          store: inmemory

    querier:
      query_ingesters_within: 5m

    query_range:
      align_queries_with_step: true

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

    limits_config:
      retention_period: 168h
