apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'app-services'
        static_configs:
          - targets: ['app1:8000', 'app2:8000']
